In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Load your data
data = pd.read_csv('/content/final_generated_data.csv')

# Define the features and target variable
features = ['Temperature', 'Humidity', 'ALLSKY_SFC_UVB', 'ALLSKY_SFC_UV_INDEX', 'ALLSKY_SFC_UVA',
            'QV2M', 'RH2M', 'PRECTOTCORR', 'WS10M', 'year', 'month', 'day', 'hour', 'weekday', 'Inflation']
target = 'Load'



In [44]:

# Initialize the scaler for features
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data[features])
scaled_data

array([[0.30862126, 0.80084211, 0.34544254, ..., 0.56557943, 0.69926422,
        0.99455183],
       [0.24814725, 0.7046667 , 0.0552311 , ..., 0.58286217, 0.96087521,
        0.99286375],
       [0.28695336, 0.95700812, 0.13330878, ..., 0.07066197, 0.62179829,
        0.99744067],
       ...,
       [0.68230535, 0.68214733, 0.60161543, ..., 0.55611048, 0.23590334,
        0.99802298],
       [0.39667995, 0.67158868, 0.46392735, ..., 0.52751575, 0.26082919,
        0.        ],
       [0.60852278, 0.81076644, 0.74964264, ..., 0.54457186, 0.32938035,
        0.99485173]])

In [46]:

# Initialize the scaler for target variable (Load)
target_scaler = MinMaxScaler()
scaled_target = target_scaler.fit_transform(data[[target]])
scaled_target

array([[0.74610131],
       [0.71835752],
       [0.17583076],
       ...,
       [0.68681019],
       [0.59526662],
       [0.77280826]])

In [47]:

# Split the data into features (X) and target variable (y)
X = scaled_data
y = scaled_target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)


In [48]:

# SVM Model
svm_model = SVR(kernel='rbf')
svm_model.fit(X_train, y_train.ravel())
y_pred_svm = svm_model.predict(X_test)


In [52]:

# Inverse transform predictions and actual values
y_pred_inv_svm = target_scaler.inverse_transform(y_pred_svm.reshape(-1, 1)).flatten()
y_test_inv = target_scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()

y_pred_inv_svm,y_test_inv

(array([31038.32623297, 58648.82832859, 42997.52941424, ...,
        56154.30542621, 56510.25004161, 61521.88646651]),
 array([28538.068, 57533.047, 39124.484, ..., 56719.125, 51406.29 ,
        61710.12 ]))

In [53]:

# Calculate metrics
rmse_svm = np.sqrt(mean_squared_error(y_test_inv, y_pred_inv_svm))
r2_svm = r2_score(y_test_inv, y_pred_inv_svm)
print(f'SVM Model - RMSE: {rmse_svm}, R²: {r2_svm}')

SVM Model - RMSE: 3207.657452828967, R²: 0.948263067320893
