In [73]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load your data
data = pd.read_csv('/content/final_generated_data.csv')

# Define the features and target variable
features = ['Temperature', 'Humidity', 'ALLSKY_SFC_UVB', 'ALLSKY_SFC_UV_INDEX', 'ALLSKY_SFC_UVA',
            'QV2M', 'RH2M', 'PRECTOTCORR', 'WS10M', 'year', 'month', 'day', 'hour', 'weekday', 'Inflation']
target = 'Load'



In [74]:
# Initialize the scaler for features
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data[features])
scaled_data

array([[0.30862126, 0.80084211, 0.34544254, ..., 0.56557943, 0.69926422,
        0.99455183],
       [0.24814725, 0.7046667 , 0.0552311 , ..., 0.58286217, 0.96087521,
        0.99286375],
       [0.28695336, 0.95700812, 0.13330878, ..., 0.07066197, 0.62179829,
        0.99744067],
       ...,
       [0.68230535, 0.68214733, 0.60161543, ..., 0.55611048, 0.23590334,
        0.99802298],
       [0.39667995, 0.67158868, 0.46392735, ..., 0.52751575, 0.26082919,
        0.        ],
       [0.60852278, 0.81076644, 0.74964264, ..., 0.54457186, 0.32938035,
        0.99485173]])

In [75]:

# Initialize the scaler for target variable (Load)
target_scaler = MinMaxScaler()
scaled_target = target_scaler.fit_transform(data[[target]])

# Split the data into features (X) and target variable (y)
X = scaled_data
y = scaled_target


In [76]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
X_train, X_test, y_train, y_test


(array([[0.30862126, 0.80084211, 0.34544254, ..., 0.56557943, 0.69926422,
         0.99455183],
        [0.24814725, 0.7046667 , 0.0552311 , ..., 0.58286217, 0.96087521,
         0.99286375],
        [0.28695336, 0.95700812, 0.13330878, ..., 0.07066197, 0.62179829,
         0.99744067],
        ...,
        [0.38640222, 0.86757635, 0.24625938, ..., 0.53165611, 0.02676503,
         0.        ],
        [0.23578813, 0.97845467, 0.13904114, ..., 0.76738801, 0.98335728,
         0.        ],
        [0.3265234 , 0.95852083, 0.14218767, ..., 0.44731694, 0.4365725 ,
         0.        ]]),
 array([[0.29038996, 0.968414  , 0.14379723, ..., 0.42098841, 0.94655761,
         0.        ],
        [0.18249151, 0.7175644 , 0.00505091, ..., 0.45927141, 0.21177542,
         0.99867058],
        [0.23892258, 0.8796117 , 0.13001646, ..., 0.92299108, 0.60995916,
         0.99760404],
        ...,
        [0.68230535, 0.68214733, 0.60161543, ..., 0.55611048, 0.23590334,
         0.99802298],
        [0.3

In [77]:
# ANN-Adam Model
ann_adam_model = MLPRegressor(hidden_layer_sizes=(150,), activation='relu', solver='adam',
                              max_iter=2000, random_state=0)
ann_adam_model.fit(X_train, y_train.ravel())
y_pred_ann_adam = ann_adam_model.predict(X_test)



In [78]:

# Inverse transform predictions and actual values
y_pred_inv_ann_adam = target_scaler.inverse_transform(y_pred_ann_adam.reshape(-1, 1)).flatten()
y_test_inv = target_scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()
y_pred_inv_ann_adam,y_test_inv


(array([32492.34139929, 60674.89642993, 43044.58137145, ...,
        59752.30040163, 57852.06707563, 64455.5200832 ]),
 array([28538.068, 57533.047, 39124.484, ..., 56719.125, 51406.29 ,
        61710.12 ]))

In [79]:
# Calculate metrics
rmse_ann_adam = np.sqrt(mean_squared_error(y_test_inv, y_pred_inv_ann_adam))
r2_ann_adam = r2_score(y_test_inv, y_pred_inv_ann_adam)
print(f'ANN-Adam Model - RMSE: {rmse_ann_adam}, R²: {r2_ann_adam}')

ANN-Adam Model - RMSE: 3561.048144075809, R²: 0.9362352883005485
